#####################################################################################################
# If master change_log_for_auto_updated.html changes merge master to HTMLhelp (kicking off publishing the Help files)
branches:
  only:
    - master

only_commits:
  files:
    - change_log_for_auto_updated.html

# Public Access Token giving AppVeyor write access to https://gitlab.com/mr_belowski/CrewChiefV4
environment:
  access_token:
    secure: qv5Nyfv8ZnjjHYdyl4Kw0NTn3L62r6i55tmYyqbMGpY=

  # Empty build script to avoid error "Specify which project or solution file to use because the folder contains more than one project or solution file"
build_script:
- cmd: >-
    cd .  

on_finish:
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://oauth2:$($env:access_token)@gitlab.com`n" -NoNewline
  - git config --global user.email "crewchiefTony@outlook.com"
  - git config --global user.name "Tony Whitley"
  - git checkout HTMLhelp
  - git merge origin/master
  # git diff --quiet && git diff --staged --quiet ensures only commit if files changed
  - git diff --quiet && git diff --staged --quiet || git commit -am "Appveyor merge master change_log_for_auto_updated.html" && git push
